### ISSUE TITLE
It's Friday 

### ISSUE THREAD

**Issue by Mat-lyons** [vend/vend-number#16]
![Friday](https://media.giphy.com/media/3o7TKNQ0xX1q0jLEf6/source.gif)

@aarr0n @unkillbob @riaannz  Hope you guys are doing good!

**Comment by dominics** [comment]
![](http://www.reactiongifs.com/r/amusd.gif)

Post here if you still have notifications turned on :)

**Comment by joanna1010** [comment]
![slotthhhhh](https://cloud.githubusercontent.com/assets/5986383/20614346/40dd39bc-b332-11e6-93f6-425598b48155.gif)

**Comment by rafaelmagu** [comment]
![thumbs-up](https://cloud.githubusercontent.com/assets/197444/20614442/697cc60c-b333-11e6-86ed-a74674d84f96.gif)

**Comment by NZKoz** [comment]
New phone, who dis?

**Comment by vend-interview-candidate** [comment]
getting these notifications



Cheers




Dempsey Malae

IT Manager

+64 9 889 0189



www.vendhq.com <http://vendhq.com/>  |  #retailsuccess
<https://twitter.com/search?q=retailsuccess>  |    Watch the video
<https://www.youtube.com/watch?v=DGmfe2-1q-0>

**Comment by yannkechichian** [comment]
Happy Friday!

Miss you guys.

**Comment by tenitski** [comment]
![](https://s-media-cache-ak0.pinimg.com/originals/62/89/ab/6289ab28e37d8b647607123aa53fa767.gif)

**Comment by jamsinclair** [comment]
Howdy y'all :smile_cat:, gotta get down on Friday! 

![Friday yeah](https://lh4.googleusercontent.com/proxy/DpSpIDscym0E4L4o-gb5CMKV_TXhlhFCB_YjFp_wqUg5dX-FWb1Xnj10lx0qhMeA0KIzNpCQhWiAQKgykYBugGuWuIpN7LGybOuCID2DrRolutntJS9TE6pm5CPQcmlhIY3Els5zc8lWt0ynraJKeBi3FgEIZaWdwkl4WU2WDWp0WJgVMgznBi_99pMfgRcCZgifQ4lTVT1If_HvxycSZj6nXXINpCrt6_ovoiyRnog=w260-h146-nc]

**Comment by unkillbob** [comment]
![I approve of this thread](https://media.giphy.com/media/12mylx6KC3Vanu/giphy.gif)

**Comment by pzurek** [comment]
![hihihi](https://cloud.githubusercontent.com/assets/10070/20616429/303661a0-b347-11e6-9442-eebb3c73c8e5.gif)

**Comment by aarr0n** [comment]
![](https://media2.giphy.com/media/ENagATV1Gr9eg/giphy.gif)

**Comment by rubeVend** [comment]
![fail-camera](https://cloud.githubusercontent.com/assets/20550500/20651970/52f2d272-b555-11e6-865d-955fbf67f06c.gif)
